### PR TITLE
Minor updates - added responsiveness to the previous

### PR DESCRIPTION
**Pull request by yokwejuste**
Thanks the responsive bootstrap NavBar and some custom CSS, I perform the responsiveness of the podcast basic items.
A code illustration below:
carbon
The mobile view and its effects look like this: 
me

### CODE REVIEW

**Review by godsakani — COMMENTED** [review]
Great
i see the search icon out of the search bar in mobile view?

**Review by godsakani — CHANGES_REQUESTED** [review]
Cool sir
I notice you used a search icon to collapse the search bar in the mobile view .
Can use a different menu icon ?

**Comment by yokwejuste** [comment]
> Cool sir I notice you used a search icon to collapse the search bar in the mobile view . Can use a different menu icon ?
Here I opted to use a search icon because we are trying to implement a search here. So why using the menu hamburger ? I guess this one looks prettier. 

But you're right in your suggestion because in the drop down there are 2 items which looks much more like a menu. But as suggestion I'll say let's leave it now like this it's just a minor property. If everything fits t the requirements for now, 🥰merge!

**Comment by godsakani** [comment]
ok cool.
I notice the designer never provided the way it needs to look like in mobile view.

**Review by godsakani — APPROVED** [review]

**Pull request merged**
