### PR TITLE
Side content

### PR DESCRIPTION
**Pull request by godsakani**
## Changes
- Added Side Content
- Reduce player Height

## Screenshot
update

### CODE REVIEW

**Comment by godsakani** [comment]
Ok @yokwejuste  thank you for these am on it

**Comment by godsakani** [comment]
hi @yokwejuste 
did you succeed to have the font type used?

**Review by Sanix-Darker — CHANGES_REQUESTED** [review]
Hello, you may face some conflicts, but don't worry , you just have to move your actual code to the root dir !
I deleted the .old directory since it was useless now !
Please ping me if the resolving is not going good !
Thanks !

**Comment by yokwejuste** [comment]
@godsakani seems like you got some merge conflicts now!?

**Comment by yokwejuste** [comment]
> hi @yokwejuste did you succeed to have the font type used?

Not really, I'm trying to adapt for this, soon the PR will be completed

**Pull request closed without merging**
