### PR TITLE
Made an onscroll view effect for header.

### PR DESCRIPTION
**Pull request by yokwejuste**
## Description
On scrolling on the podcast, the header background was kept transparent which made the look some how obsolete. This PR is to solve this problem.

### CODE REVIEW

**Comment by yokwejuste** [comment]
@godsakani may you review these changes made?

**Comment by godsakani** [comment]
> @godsakani may you review these changes made?

ok sir

**Review by godsakani — COMMENTED** [review]
Hello sir 
This is awesome. 
it will be good if you can add a screenshot there too. 
I wish to ask that the target I saw is just windows. what happens when it comes to mobile view and other devices?. 
Does the scroll effect work for all devices?

**Comment by yokwejuste** [comment]
image
concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.

**Comment by godsakani** [comment]
> image concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.

Awsome sir
Ok sir I was asking to know because I saw only windows so I thought it applied for all.

**Comment by godsakani** [comment]
> image concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.

Hello @yokwejuste 
I noticed a transition and color that is a type.
wish to ask why you added that transition?
colo

**Comment by yokwejuste** [comment]
> > image concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.
> 
> Hello @yokwejuste I noticed a transition and color that is a type. wish to ask why you added that transition? colo

Acttually i did this because it looks prettier and the effect is cool. It makes the UX more friendly

**Comment by godsakani** [comment]
> > > image concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.
> > 
> > 
> > Hello @yokwejuste I noticed a transition and color that is a type. wish to ask why you added that transition? colo
> 
> Acttually i did this because it looks prettier and the effect is cool. It makes the UX more friendly

Awesome @yokwejuste 
I get it now you can think of reducing the color intensity or changing it. Because is too intense.
I wish to propose if you can use the same color for the background and reduce the intensity or change its opacity to make it blend. How do see it?

**Comment by yokwejuste** [comment]
> > > > image concerning the mobile view and other devices, the site is not much that way responsive, I'll work on it later. but for no please lets focus on the desktop. concerning the mobile will just be some bunch of extra styling.
> > > 
> > > 
> > > Hello @yokwejuste I noticed a transition and color that is a type. wish to ask why you added that transition? colo
> > 
> > 
> > Acttually i did this because it looks prettier and the effect is cool. It makes the UX more friendly
> 
> Awesome @yokwejuste I get it now you can think of reducing the color intensity or changing it. Because is too intense. I wish to propose if you can use the same color for the background and reduce the intensity or change its opacity to make it blend. How do see it?

That's awesome thoughts. What i'll do is that I'll reduce thew opacity of the color. 

May I ask @godsakani if the previous one was before the search update was appropriate?

**Comment by godsakani** [comment]
> 

Yeah, it was ok. We can used it back

**Pull request merged**
