### PR TITLE
making search filter work

### PR DESCRIPTION
**Pull request by godsakani**
hello @Sanix-Darker , @yokwejuste ,
don't merge the PR is the code Implemented for the search functionality and it didn't work.
will need your help here please check and give your corrections.

### CODE REVIEW

**Comment by yokwejuste** [comment]
Hey @godsakani what's the current output or result, can i have a look on it?

**Comment by godsakani** [comment]
> Hey @godsakani what's the current output or result, can i have a look on it?


Err1
 
that is the error am recieving

**Comment by godsakani** [comment]
> 
Err1

New error how do i export a function

**Comment by godsakani** [comment]
Hello @yokwejuste , @Sanix-Darker 

i just push the changes

**Pull request closed without merging**
