### PR TITLE
minor changes for code improvement.

### PR DESCRIPTION
**Pull request by yokwejuste**
some code improvement done in answer to issue #8 .

### CODE REVIEW

**Comment by yokwejuste** [comment]
@godsakani a review from yours is needed from you for this PR

**Review by godsakani — CHANGES_REQUESTED** [review]
Yoo steve this PR is not required
i already did the correction and modification of this.
currently am working with the static list so please you can close the PR

**Comment by yokwejuste** [comment]
> Yoo steve this PR is not required i already did the correction and modification of this. currently am working with the static list so please you can close the PR

Alright! then do it let me update mine.

**Comment by godsakani** [comment]
> > Yoo steve this PR is not required i already did the correction and modification of this. currently am working with the static list so please you can close the PR
> 
> Alright! then do it let me update mine.

Ok

**Pull request closed without merging**
