### PR TITLE
Feat: Podcasts player implementation.

### PR DESCRIPTION
**Pull request by yokwejuste**
The podcast player has being done in relation to the issue #19 .  A preview of its features can be seen below or to the link: https://go-records.me/podcasts/ 
ezgif com-gif-maker

Waiting for review by @godsakani  and @Sanix-Darker

### CODE REVIEW

**Review by godsakani — CHANGES_REQUESTED** [review]
Good one here @yokwejuste .
Have you check on the forward button?
Each time I press the forward button it shows undefined and stop playing.

Then the link to the download button on the tracks still link to your portfolio.

Then if you notice the height of the player is taken much space. I wish to fine out if we will correct the designs but after or how do you intern to do it?

**Comment by yokwejuste** [comment]
> Good one here @yokwejuste . Have you check on the forward button? Each time I press the forward button it shows undefined and stop playing.
> 
> Then the link to the download button on the tracks still link to your portfolio.
> 
> Then if you notice the height of the player is taken much space. I wish to fine out if we will correct the designs but after or how do you intern to do it?

That's just the index of the song loading. That's what I was talking about when I said a network problem

**Comment by yokwejuste** [comment]
> Good one here @yokwejuste . Have you check on the forward button? Each time I press the forward button it shows undefined and stop playing.
> 
> Then the link to the download button on the tracks still link to your portfolio.
> 
> Then if you notice the height of the player is taken much space. I wish to fine out if we will correct the designs but after or how do you intern to do it?

As for the player's height I guess it's okay, lately we'll make it in such a way that it can be lower or hidden by the user. 


We should have a more elaborates discussion for that music not loading.

**Comment by godsakani** [comment]
> 
Ok @yokwejuste 
is just the forward button right?

**Comment by godsakani** [comment]
> > > 
> > 
> > 
> > Ok @yokwejuste is just the forward button right?
> 
> Backward too. We'll need some kind of serialization for these audios.
ok let check some ideas online

**Comment by godsakani** [comment]
Good job here @yokwejuste

**Pull request merged**
