### PR TITLE
Feat: Bringing better responsiveness to the podcasts

### PR DESCRIPTION
**Pull request by yokwejuste**
## Problem

I noticed the podcasts had some failures when it comes to adapting to different screen sizes depending on the device it is opened on.

## Solution
As solution for this issue faced this PR is brought up.

### CODE REVIEW

**Comment by yokwejuste** [comment]
@godsakani don't yet merge this PR #41, some basic fixes are to brought to it.

**Review by godsakani — COMMENTED** [review]
Is it ok and are you done with PR so i merged it

**Review by Sanix-Darker — CHANGES_REQUESTED** [review]
Hello, you may face some conflicts, but don't worry , you just have to move your actual code to the root dir !
I deleted the .old directory since it was useless now !
Please ping me if the resolving is not going good !
Thanks !

**Comment by godsakani** [comment]
Hi @Sanix-Darker  wish to suggest that since you are not yet done with cleaning of the code . Is possible we wait and keep our changes in our repo so when you are done we open the PR?

**Pull request closed without merging**
